server:
  port: 8181

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: BOOKING
          uri: lb://BOOKING
          predicates:
            - Path=/booking/**
        - id: NOTIFICATION
          uri: lb://NOTIFICATION
          predicates:
            - Path=/notification/**
        - id: AUTH
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://3.1.8.197:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
